[workspace]
name = "tclean"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = ">=3.12"
pandas = ">=3.0.3"
pytest = ">=8.3.5"
ruff = ">=0.9.9"
mypy = ">=1.15.0"
pandera = ">=0.31.1"

[feature.dev.dependencies]
pytest = "*"
hatchling = "*"

[feature.dev.pypi-dependencies]
tclean = { path = ".", editable = true }

[environments]
default = { features = ["dev"] }

[tasks]
test = "pytest"
lint = "ruff check ."
format = "ruff format ."
format-check = "ruff format --check ."